using System.Text.Json;
using FluentAssertions;
using MicroPlumberd;
using Microsoft.Extensions.Logging.Abstractions;
using ModelingEvolution.Ipv4;
using RocketWelder.SDK.Abstractions;
using RocketWelder.SDK.Automation;

namespace RocketWelder.SDK.Automation.Tests;

/// <summary>
/// Guardrail tests for <see cref="PeripheralDevicesReadModel"/>.
///
/// <para>
/// <b>[OutputStream("PeripheralDevicesReadModel_v1")]</b> on the read model is FROZEN —
/// changing it silently renames the merged stream and breaks all catch-up subscriptions.
/// The reflection guard below catches that at compile-time in CI.
/// </para>
///
/// <para>
/// The replay tests exercise the <c>Given(Metadata, object)</c> dispatcher generated by
/// MicroPlumberd's <c>[EventHandler]</c> source generator, covering the same deserialization
/// path that production catch-up subscriptions traverse. The read model is constructed
/// in isolation (no EventStore) using <see cref="NoOpDeviceSignalPublisher"/> and
/// <see cref="NullLogger{T}"/>.
/// </para>
/// </summary>
public class PeripheralDevicesReadModelTests
{
    // ── Guardrail: [OutputStream("PeripheralDevicesReadModel_v1")] is FROZEN ──

    [Fact]
    public void ReadModel_must_carry_OutputStream_PeripheralDevicesReadModel_v1()
    {
        var attr = typeof(PeripheralDevicesReadModel)
            .GetCustomAttributes(typeof(OutputStreamAttribute), inherit: false)
            .Cast<OutputStreamAttribute>()
            .FirstOrDefault();

        attr.Should().NotBeNull(
            "removing [OutputStream] silently renames the merged stream and breaks catch-up subscriptions");
        attr!.OutputStreamName.Should().Be("PeripheralDevicesReadModel_v1",
            "the persisted stream name is frozen at \"PeripheralDevicesReadModel_v1\"");
    }

    // ── Replay tests ──────────────────────────────────────────────────────────

    [Fact]
    public async Task ReadModel_replay_Given_Created_adds_item()
    {
        var deviceId = DeviceId.New("FroniusWeldingMachine_TPS5000");
        var rm = MakeReadModel();

        await rm.Given(Meta(deviceId), new PeripheralDeviceCreated("FroniusWeldingMachine_TPS5000", "IWeldingMachine", "Welder1", 1));

        rm.Items.Should().HaveCount(1);
        rm.Items[0].Name.Should().Be("Welder1");
        rm.Items[0].DeviceType.Should().Be("FroniusWeldingMachine_TPS5000");
        rm.Items[0].InterfaceType.Should().Be("IWeldingMachine");
        rm.Items[0].Number.Should().Be(1);
        rm.GetById(deviceId).Should().NotBeNull();
    }

    [Fact]
    public async Task ReadModel_replay_Given_Renamed_updates_name()
    {
        var deviceId = DeviceId.New("FroniusWeldingMachine_TPS5000");
        var rm = MakeReadModel();

        await rm.Given(Meta(deviceId), new PeripheralDeviceCreated("FroniusWeldingMachine_TPS5000", "IWeldingMachine", "WelderA", 1));
        await rm.Given(Meta(deviceId), new PeripheralDeviceRenamed("WelderB"));

        rm.Items.Should().HaveCount(1);
        rm.Items[0].Name.Should().Be("WelderB");
    }

    [Fact]
    public async Task ReadModel_replay_Given_Configured_patches_config()
    {
        var deviceId = DeviceId.New("FroniusWeldingMachine_TPS5000");
        var rm = MakeReadModel();

        await rm.Given(Meta(deviceId), new PeripheralDeviceCreated("FroniusWeldingMachine_TPS5000", "IWeldingMachine", "Welder1", 1));

        var patch = new ConfigSet(new IpProperty(Ipv4Address.Parse("192.168.1.42", null)));
        await rm.Given(Meta(deviceId), new PeripheralDeviceConfigured(patch, []));

        var item = rm.GetById(deviceId);
        item.Should().NotBeNull();
        item!.Config.Get<IpProperty, Ipv4Address>().Should().Be(Ipv4Address.Parse("192.168.1.42", null));
    }

    [Fact]
    public async Task ReadModel_replay_Given_Removed_clears_item()
    {
        var deviceId = DeviceId.New("FroniusWeldingMachine_TPS5000");
        var rm = MakeReadModel();

        await rm.Given(Meta(deviceId), new PeripheralDeviceCreated("FroniusWeldingMachine_TPS5000", "IWeldingMachine", "Welder1", 1));
        await rm.Given(Meta(deviceId), new PeripheralDeviceRemoved());

        rm.Items.Should().BeEmpty();
        rm.GetById(deviceId).Should().BeNull();
    }

    [Fact]
    public async Task ReadModel_replay_two_devices_tracked_independently()
    {
        var id1 = DeviceId.New("FroniusWeldingMachine_TPS5000");
        var id2 = DeviceId.New("FroniusWeldingMachine_iWave");
        var rm = MakeReadModel();

        await rm.Given(Meta(id1), new PeripheralDeviceCreated("FroniusWeldingMachine_TPS5000", "IWeldingMachine", "Welder1", 1));
        await rm.Given(Meta(id2), new PeripheralDeviceCreated("FroniusWeldingMachine_iWave", "IWeldingMachine", "Welder2", 2));
        await rm.Given(Meta(id1), new PeripheralDeviceRemoved());

        rm.Items.Should().HaveCount(1, "only Welder2 remains after Welder1 is removed");
        rm.Items[0].Name.Should().Be("Welder2");
        rm.GetById(id2).Should().NotBeNull();
        rm.GetById(id1).Should().BeNull();
    }

    [Fact]
    public async Task ReadModel_replay_unknown_device_type_does_not_throw()
    {
        // RebuildAsync logs a warning when the device type is not in the registry but
        // must never throw — replay must be total and forward-compatible (new nodes receiving
        // old streams before a plugin is installed must not crash the subscription).
        var deviceId = DeviceId.New("UnknownVendorDevice");
        var rm = MakeReadModel(registry: new DeviceTypeRegistry()); // empty registry

        var act = async () => await rm.Given(Meta(deviceId),
            new PeripheralDeviceCreated("UnknownVendorDevice", "IUnknown", "Mystery1", 1));

        await act.Should().NotThrowAsync(
            "unknown device type is logged as a warning; the item is still tracked in Items");
        rm.Items.Should().HaveCount(1, "item is added even when the factory cannot be resolved");
        // RebuildAsync returns early (warning-log only) when type is missing — status stays Disconnected.
        // Only factory exceptions set Status.Error; registry miss does not.
        rm.Items[0].Status.Should().Be(PeripheralDeviceStatus.Disconnected,
            "status stays Disconnected when RebuildAsync exits early due to missing registry entry");
        rm.Items[0].Instance.Should().BeNull("no device instance is created when the type is unknown");
    }

    // ── Wire-shape round-trip (JSON serialization through MicroPlumberd path) ─

    [Fact]
    public async Task ReadModel_replay_survives_JSON_serialization_round_trip()
    {
        // Prove that the event payloads the read model receives in production
        // (JSON bytes → CLR type) deserialize correctly. If a field name changes, this fails.
        var typeRegistry = new Dictionary<string, Type>(StringComparer.OrdinalIgnoreCase)
        {
            [nameof(PeripheralDeviceCreated)] = typeof(PeripheralDeviceCreated),
            [nameof(PeripheralDeviceRenamed)] = typeof(PeripheralDeviceRenamed),
        };

        var deviceId = DeviceId.New("FroniusWeldingMachine_TPS5000");
        var rm = MakeReadModel();

        // Serialize → deserialize as MicroPlumberd does
        object Roundtrip(string typeName, object ev)
        {
            var bytes = JsonSerializer.SerializeToUtf8Bytes(ev);
            return JsonSerializer.Deserialize(bytes, typeRegistry[typeName])!;
        }

        await rm.Given(Meta(deviceId),
            Roundtrip(nameof(PeripheralDeviceCreated),
                new PeripheralDeviceCreated("FroniusWeldingMachine_TPS5000", "IWeldingMachine", "Welder1", 1)));

        await rm.Given(Meta(deviceId),
            Roundtrip(nameof(PeripheralDeviceRenamed), new PeripheralDeviceRenamed("WelderRenamed")));

        rm.Items.Should().HaveCount(1);
        rm.Items[0].Name.Should().Be("WelderRenamed");
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /// <summary>
    /// Builds a <see cref="Metadata"/> for the given device id. The source stream id
    /// follows the MicroPlumberd convention for aggregate streams:
    /// <c>"StreamCategory-{id}"</c> where the part after the first <c>-</c> is what
    /// <see cref="Metadata.StreamId{T}"/> parses. The data <see cref="JsonElement"/> must
    /// be a valid (non-Undefined) JSON object; <see cref="Metadata.StreamId{T}"/> calls
    /// <c>TryGetProperty</c> on it and throws if the element is <c>JsonValueKind.Undefined</c>.
    /// </summary>
    private static Metadata Meta(DeviceId deviceId) =>
        new Metadata(Guid.NewGuid(), Guid.Empty, 0, null,
            $"PeripheralDevice-{deviceId}", JsonDocument.Parse("{}").RootElement);

    private static PeripheralDevicesReadModel MakeReadModel(DeviceTypeRegistry? registry = null) =>
        new PeripheralDevicesReadModel(
            registry ?? new DeviceTypeRegistry(),
            new NoOpDeviceSignalPublisher(),
            NullLogger<PeripheralDevicesReadModel>.Instance);
}
